#!/bin/sh /etc/rc.common
START=99
STOP=10
USE_PROCD=1

start_service() {
 if [ -s /root/dja-backhaul/ssid ] && [ -s /root/dja-backhaul/password ]; then
  procd_open_instance backhaul
  procd_set_param command /root/dja-backhaul/run.sh
  procd_set_param respawn 3600 10 0
  procd_set_param term_timeout 15
  procd_close_instance
 fi

 procd_open_instance monitor
 procd_set_param command /usr/bin/lua /root/dja-backhaul/backhaul-status-monitor.lua
 procd_set_param respawn 3600 10 0
 procd_set_param term_timeout 5
 procd_close_instance

 procd_open_instance webui-graphs
 procd_set_param command /root/dja-backhaul/restore-webui-graphs.sh
 procd_set_param respawn 3600 10 0
 procd_set_param term_timeout 5
 procd_close_instance
}
